[tools]
actionlint = "latest"
chezmoi = "latest"
deno = "latest"
dua = "latest"
fastfetch = "latest"
gh = "latest"
go = "latest"
just = "latest"
ktlint = "latest"
lazygit = "latest"
lsd = "latest"
node = "latest"
pnpm = "latest"
powershell-core = "latest"
railway = "latest"
tokei = "latest"
typst = "latest"
uv = "latest"
zoxide = "latest"
dust = "latest"
bun = "latest"
imagemagick = "latest"
curlie = "latest"
delta = "latest"
lazydocker = "latest"
lazyssh = "latest"
lazyjournal = "latest"
gradle-profiler = "latest"
oxipng = "latest"
mold = "latest"
