[tools]
actionlint = "latest"
chezmoi = "latest"
deno = "2.2.2"
fastfetch = "latest"
gh = "latest"
go = "latest"
just = "latest"
ktlint = "latest"
lazygit = "latest"
lsd = "latest"
node = "latest"
pnpm = "latest"
powershell-core = "latest"
railway = "latest"
tokei = "latest"
typst = "latest"
uv = "latest"
zoxide = "0.9.6"
